=begin
#OpenAPI Petstore

#This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'pet_store_client/api_client'
require 'pet_store_client/api_error'
require 'pet_store_client/version'
require 'pet_store_client/configuration'

# Models
require 'pet_store_client/models/api_response'
require 'pet_store_client/models/category'
require 'pet_store_client/models/inline_object'
require 'pet_store_client/models/inline_object1'
require 'pet_store_client/models/order'
require 'pet_store_client/models/pet'
require 'pet_store_client/models/tag'
require 'pet_store_client/models/user'

# APIs
require 'pet_store_client/api/pet_api'
require 'pet_store_client/api/store_api'
require 'pet_store_client/api/user_api'

module PetStoreClient
  class << self
    # Customize default settings for the SDK using block.
    #   PetStoreClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
